"""Generates a Lua file with Lua Language Server annotations based on extension_api.json and Godots docs"""

import os
import json
from textwrap import dedent

from json_types import *
import generate_lua_docs

SRC_DIR = os.path.dirname(__file__)
PROJECT_ROOT = os.path.join(SRC_DIR, "..", "..")
DEST_DIR = os.path.join(PROJECT_ROOT, "addons", "lua-gdextension", "lua_api_definitions")
API_JSON_PATH = os.path.join(PROJECT_ROOT, "lib", "godot-cpp", "gdextension", "extension_api.json")
LUA_CLASSES_PATH = os.path.join(PROJECT_ROOT, "doc_classes")

OPERATOR_MAP = {
    ## LLS doesn't really support equality operators: https://github.com/LuaLS/lua-language-server/issues/1882
    # "==": "eq",
    # "<": "lt",
    # "<=": "le",

    "+": "add",
    "-": "sub",
    "*": "mul",
    "/": "div",
    "%": "mod",
    "**": "pow",
    "unary-": "unm",

    "&": "band",
    "|": "bor",
    "^": "bxor",
    "~": "bnot",
    "<<": "shl",
    ">>": "shr",
}

LUA_KEYWORD_MAP = {
    "end": "_end",
    "function": "_function",
    "in": "_in",
    "local": "_local",
    "repeat": "_repeat",
}

MANUALLY_DEFINED_UTILITY_FUNCTIONS = {
    "typeof",
}

PREAMBLE = [
    "--- This file was automatically generated by tools/code_generation/generate_lua_godot_api.py",
    "--- @meta",
    "--- @diagnostic disable: undefined-doc-name, duplicate-doc-field, duplicate-doc-alias",
]

def main():
    with open(API_JSON_PATH, encoding="utf-8") as f: extension_api = json.load(f)

    # classes = []

    def write_lua_comment(dir, name):
        try:
            lua_comment = generate_lua_docs.get_godot_class_lua(name)
        except Exception as e:
            print(f"Failed to get class data for {name}")
            return

        with open(os.path.join(dir, f"{name}.lua"), "w") as f:
            f.write(lua_comment)

    # # builtin_classes (variants)
    # variants = extension_api["builtin_classes"]
    # variants_dir = os.path.join(DEST_DIR, "variants")
    # os.makedirs(variants_dir, exist_ok=True)
    # for i in variants:
    #     with open(os.path.join(variants_dir, f"{i}.lua"), "w") as f:
    #         write_lua_comment(f, i)

    write_lua_comment(DEST_DIR, "@GlobalScope")

    # classes (& singletons)
    classes = extension_api["classes"] #, extension_api["singletons"]
    classes_dir = os.path.join(DEST_DIR, "classes")
    os.makedirs(classes_dir, exist_ok=True)
    for cls in classes:
        name = cls["name"]
        write_lua_comment(classes_dir, name)

    # .gdignore
    with open(os.path.join(DEST_DIR, ".gdignore"), "w") as f: f.write("")

# TODO: update from rst special typings to xml
# def _arg_type(name: str, has_default: Any = False) -> str:
#     # handle 'const' removal as 'const' isn't present in Lua
#     if "const" in name:
#         name = name.replace("const", "").strip()
    
#     if "**" in name: # the closest thing to multi-level & number** pointers in Lua would be references nested in a table
#         if "int" in name:
#             arg_type = "Array[number]"
#         else:
#             arg_type = "Array[any]"
        
#     elif "int" in name: # Lua doesn't differentiate between integers and floating-point numbers internally
#         arg_type = "number"

#     elif name == "Variant":
#         arg_type = "any"

#     elif name == "void*": # 'void*' is a pointer to any type
#         arg_type = "any" 

#     elif name.startswith("typedarray::"): # express 'typedarray's as 'Array[T]'
#         arg_type = f"Array[{name[len("typedarray::"):]}]"

#     else: # general case cleanup
#         arg_type = name.replace(",", " | ").replace("enum::", "").replace("bitfield::", "")
    
#     if has_default: 
#         arg_type += '?'

#     if "*" in arg_type: # Lua uses references not pointers, so theres no need for pointers
#         arg_type = arg_type.replace("*", "").strip()

#     # print(f"{name} -> {arg_type}")
#     return arg_type

if __name__ == "__main__":
    main()
